LaboratorioPWA/Models/juego.cs
namespace LaboratorioPWA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("juego")]
    public partial class juego
    {
        [Key]
        public int idjuego { get; set; }

        [StringLength(75)]
        public string nomJuego { get; set; }

        public int? idcategoria { get; set; }

        public double? precio { get; set; }

        public int? existencias { get; set; }

        [StringLength(200)]
        public string imagen { get; set; }

        public virtual categoria categoria { get; set; }
    }
}

LaboratorioPWA/Controllers/JuegosController.cs
using LaboratorioPWA.Models;
using LaboratorioPWA.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LaboratorioPWA.Controllers
{
    public class JuegosController : Controller
    {
        private readonly RJuego db = new RJuego();
        private readonly ICrudGeneral<categoria> dbCategoria = new RCategoria();
        // GET: Juegos
        public ActionResult Index()
        {
            var respuesta = db.GetAll().Result;
            var lista = (List<juego>)respuesta;

            return View(lista);
        }
        public ActionResult JuegosSorted()
        {
            var respuesta = db.GetSortedGames().Result;
            var lista = (List<juego>)respuesta;
            return View(lista);
        }
        public ActionResult NuevoJuego()
        {
            var resp = dbCategoria.GetAll();
            if (resp.IsSuccess)
            {
                ViewBag.Categorias = (List<categoria>)resp.Result;
            }
            return View();
        }
        [HttpPost]
        public ActionResult NuevoJuego(localJuego item)
        {
            
            string fileName = Path.GetFileNameWithoutExtension(item.ImageFile.FileName);
            string extension = Path.GetExtension(item.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssffff") + extension;
            item.imageGame = "~/Images/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
            item.ImageFile.SaveAs(fileName);
            juego juego = new juego
            {
                imagen = item.imageGame,
                nomJuego = item.nomJuego,
                existencias = item.existencias,
                precio = item.precio,
                categoria = item.categoria,
                idcategoria=item.idcategoria
                
            };
            var resp = db.Post(juego);
            if (!resp.IsSuccess)
            {
                return View();
            }
            else
            {
                return Redirect("~/juegos");
            }
        }
        public ActionResult Editar(int id)
        {
            var item = (juego)db.GetById(id).Result;
            ViewBag.LastPic = item.imagen;
            var resp = dbCategoria.GetAll();
            if (resp.IsSuccess)
            {
                ViewBag.CategoriasEditar = (List<categoria>)resp.Result;
            }
            localJuego item2 = new localJuego
            {
                idJuego = id,
                nomJuego = item.nomJuego,
                existencias = (int)item.existencias
                
            };
            return View(item2);
        }
        [HttpPost]
        public ActionResult Editar(localJuego item)
        {
            if (item.ImageFile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(item.ImageFile.FileName);
                string extension = Path.GetExtension(item.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssffff") + extension;
                item.imageGame = "~/Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                item.ImageFile.SaveAs(fileName);
                juego juego = new juego
                {
                    imagen = item.imageGame,
                    nomJuego = item.nomJuego,
                    existencias = item.existencias,
                    precio = item.precio,
                    categoria = item.categoria,
                    idcategoria = (int)item.idcategoria
                };
                var resp = db.Update(juego, item.idJuego);
                if (!resp.IsSuccess)
                {
                    return View();
                }
                else
                {
                    return Redirect("~/juegos");
                }
            }
            else
            {
                var item2 = db.GetById(item.idJuego);
                var jue = (juego)item2.Result;
                jue.nomJuego = item.nomJuego;
                jue.precio = item.precio;
                jue.existencias = item.existencias;
                jue.idcategoria = item.idcategoria;
                var resp = db.Update(jue, item.idJuego);
                if (!resp.IsSuccess)
                {
                    return View();
                }
                else
                {
                    return Redirect("~/juegos");
                }
            }
        }
        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            var resp = db.Delete(id);
            return Redirect("~/juegos");
        }
    }
}

LaboratorioPWA/Views/Juegos/Editar.cshtml
@model LaboratorioPWA.Models.localJuego
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Juegos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="row">
    
    <div class="card-body">
        <div class="row" style="padding-left: 10px; padding-right: 10px;">

            <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                <label class="control-label">Nombre del juego</label>
                @Html.TextBoxFor(novojogo => novojogo.nomJuego, "", new { @class = "form-control" })
            </div>

            <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                <label class="control-label">Precio</label>
                @Html.TextBoxFor(novojogo => novojogo.precio, "", new { @class = "form-control" })
            </div>

            <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                <label class="control-label">Existencias</label>
                @Html.TextBoxFor(novojogo => novojogo.existencias, "", new { @class = "form-control" })
            </div>
            <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                <label class="control-label">Categoria</label>
                <select name="idcategoria" class="form-control">
                    @foreach (var item in ViewBag.CategoriasEditar)
                    {
                        <option value="@item.idcategoria">@item.nomCategoria</option>
                    }
                </select>
            </div>
            <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                <label class="control-label">Imagen</label>
                @Html.HiddenFor(d => d.idJuego)
                <input type="file" name="ImageFile" class="form-control" />
            </div>
            <div>
                <input class="btn btn-outline-dark" value="Guardar" type="submit" />
            </div>
        </div>
    </div>
</div>
}

LaboratorioPWA/Views/Juegos/Index.cshtml
@model List<LaboratorioPWA.Models.juego>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <p>
        <a href="~/Juegos/NuevoJuego" class="btn btn-outline-primary">Agregar Juego</a>
    </p>
</div>
<div class="table-responsive">
    <table class="table">
        <thead class="bg-dark text-white text-center">
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Nombre
                </th>
                <th>
                    Portada
                </th>
                <th>
                    Precio
                </th>
                <th>
                    Existencias
                </th>
                <th>
                    Categoria
                </th>
                <th>
                    Opciones
                </th>
            </tr>
        </thead>


        @foreach (var item in Model)
        {
    <tr>
        <td class="text-center">
            @Html.DisplayFor(modelItem => item.idjuego)
        </td>
        <td class="text-center">
            @Html.DisplayFor(modelItem => item.nomJuego)
        </td>
        <td class="text-center">
            <img src=@Url.Content(item.imagen) width="100" height="150" />
        </td>
        <td class="text-center">
            @Html.DisplayFor(modelItem => item.precio)
        </td>
        <td class="text-center">
            @Html.DisplayFor(modelItem => item.existencias)
        </td>
        <td class="text-center">
            @Html.DisplayFor(modelItem => item.categoria.nomCategoria)
        </td>
        <td class="text-center">
            <a href="~/juegos/Editar/@item.idjuego" class="btn btn-outline-primary">Editar</a>
            <a href="~/juegos/Eliminar/@item.idjuego" class="btn btn-outline-danger">Eliminar</a>
        </td>
    </tr>
        }

    </table>
</div>

LaboratorioPWA/Views/Juegos/JuegosSorted.cshtml
@model List<LaboratorioPWA.Models.juego>
@{
    ViewBag.Title = "Index";
}

<div class="table-responsive">
    <table class="table">
        <thead class="bg-dark text-white text-center">
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Nombre
                </th>
                <th>
                    Portada
                </th>
                <th>
                    Precio
                </th>
                <th>
                    Existencias
                </th>
                <th>
                    Categoria
                </th>
            </tr>
        </thead>


        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.idjuego)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.nomJuego)
                </td>
                <td class="text-center">
                    <img src=@Url.Content(item.imagen) width="100" height="150" />
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.precio)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.existencias)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.categoria.nomCategoria)
                </td>
            </tr>
        }

    </table>
</div>

LaboratorioPWA/Views/Juegos/nuevoJuego.cshtml
@model LaboratorioPWA.Models.localJuego
@{
    ViewBag.Title = "nuevoJuego";
}

<h2>Agregar Juego</h2>
@using (Html.BeginForm("NuevoJuego", "Juegos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="row">
    
    <div class="container" style="padding-top:25px;">
        <div class="card border-dark shadow">
            <div class="card-header">
                <b>Nuevo Juego</b>
            </div>
            <div class="card-body">
                <div class="row" style="padding-left: 10px; padding-right: 10px;">

                    <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                        <label class="control-label">Nombre del juego</label>
                        @Html.TextBoxFor(novojogo => novojogo.nomJuego, "", new { @class = "form-control" })
                    </div>

                    <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                        <label class="control-label">Precio</label>
                        @Html.TextBoxFor(novojogo => novojogo.precio, "", new { @class = "form-control" })
                    </div>

                    <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                        <label class="control-label">Categoria</label>
                        <select name="idcategoria" class="form-control">
                            @foreach (var item in ViewBag.Categorias)
                            {
                                <option value="@item.idcategoria">@item.nomCategoria</option>
                            }
                        </select>
                    </div>

                    <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                        <label class="control-label">Existencias</label>
                        @Html.TextBoxFor(novojogo => novojogo.existencias, "", new { @class = "form-control" })
                    </div>

                    <div class="col-xl-3 col-md-6 col-sm-12 mb-2">
                        <label class="control-label">Imagen</label>
                        @*@Html.EditorFor(d=>d.ImageFile , new { htmlAttributes = new { @class = "form-control",@type = "file"} })*@
                        <input type="file" name="ImageFile" class="form-control" />
                    </div>
                    <div>
                        <input class="btn btn-outline-dark" value="Guardar" type="submit" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}