LaboratorioPWA/Models/categoria.cs
namespace LaboratorioPWA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("categoria")]
    public partial class categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categoria()
        {
            juego = new HashSet<juego>();
        }

        [Key]
        public int idcategoria { get; set; }

        [StringLength(50)]
        public string nomCategoria { get; set; }

        [StringLength(50)]
        public string imagenCat { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<juego> juego { get; set; }
    }
}

LaboratorioPWA/Controllers/CategoriaController.cs
using LaboratorioPWA.Models;
using LaboratorioPWA.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LaboratorioPWA.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ICrudGeneral<categoria> db = new RCategoria(); 
        // GET: Categoria
        public ActionResult Index()
        {
            var items = db.GetAll().Result;
            List<categoria> item = (List<categoria>)items;
            return View(item);
        }
        public ActionResult NuevaCategoria()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NuevaCategoria(LocalCat item)
        {
            string fileName = Path.GetFileNameWithoutExtension(item.ImageFile.FileName);
            string extension = Path.GetExtension(item.ImageFile.FileName);
            fileName = fileName +DateTime.Now.ToString("yymmssffff")+ extension;
            item.imagenCat = "~/Images/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Images/"),fileName);
            item.ImageFile.SaveAs(fileName);
            categoria cat = new categoria
            {
                imagenCat = item.imagenCat,
                nomCategoria=item.nomCategoria
            };
            var resp = db.Post(cat);
            if (!resp.IsSuccess)
            {
                return View();
            }
            else
            {
                return Redirect("~/categoria");
            }
        }
        public ActionResult Editar(int id)
        {
            var item = (categoria)db.GetById(id).Result;
            ViewBag.LastPic = item.imagenCat;
            LocalCat item2 = new LocalCat
            {
                idcategoria=id,
                nomCategoria=item.nomCategoria,
            };
            return View(item2);
        }
        [HttpPost]
        public ActionResult Editar(LocalCat item)
        {
            if (item.ImageFile!=null)
            {
                string fileName = Path.GetFileNameWithoutExtension(item.ImageFile.FileName);
                string extension = Path.GetExtension(item.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssffff") + extension;
                item.imagenCat = "~/Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                item.ImageFile.SaveAs(fileName);
                categoria cat = new categoria
                {
                    imagenCat = item.imagenCat,
                    nomCategoria = item.nomCategoria
                };
                var resp = db.Update(cat,item.idcategoria);
                if (!resp.IsSuccess)
                {
                    return View();
                }
                else
                {
                    return Redirect("~/categoria");
                }
            }
            else
            {
                var item2 = db.GetById(item.idcategoria);
                var cate = (categoria)item2.Result;
                cate.nomCategoria = item.nomCategoria;
                var resp = db.Update(cate, item.idcategoria);
                if (!resp.IsSuccess)
                {
                    return View();
                }
                else
                {
                    return Redirect("~/categoria");
                }
            }
        }
        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            var resp = db.Delete(id);
            return Redirect("~/categoria");
        }
    }
}

LaboratorioPWA/Views/Categoria/Editar.cshtml
@model LaboratorioPWA.Models.LocalCat
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Categoria", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(d => d.nomCategoria)
            @Html.TextBoxFor(d => d.nomCategoria, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.imagenCat)
            @Html.HiddenFor(d=>d.idcategoria)
            @*@Html.EditorFor(d=>d.ImageFile , new { htmlAttributes = new { @class = "form-control",@type = "file"} })*@
            <input type="file" name="ImageFile" class="form-control" />
        </div>
        <br />
        <div style="text-align:right">
            <input class="btn btn-primary" value="Guardar" type="submit" />
        </div>
    </div>
}

LaboratorioPWA/Views/Categoria/Index.cshtml
@model List<LaboratorioPWA.Models.categoria>

<div class="container">
    <div style="text-align:right">
        <a href="~/Categoria/NuevaCategoria" class="btn btn-info">Nueva</a>
    </div>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Imagen</th>
                    <th>Nombre Categoria</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td><img src=@Url.Content(item.imagenCat) width="250" height="250"/></td>
                        <td>@item.nomCategoria</td>
                        <td><a href="~/categoria/editar/@item.idcategoria" class="btn btn-info">Editar</a></td>
                        <td><a href="~/categoria/eliminar/@item.idcategoria" class="btn btn-danger">Eliminar</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

LaboratorioPWA/Views/Categoria/NuevaCategoria.cshtml
@model LaboratorioPWA.Models.LocalCat

@{
    ViewBag.Title = "Nueva categoria";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("NuevaCategoria","Categoria",FormMethod.Post, new {enctype = "multipart/form-data"  }))
{
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(d => d.nomCategoria)
            @Html.TextBoxFor(d=>d.nomCategoria, "", new { @class= "form-control"})
            @Html.LabelFor(d=>d.imagenCat)
            @*@Html.EditorFor(d=>d.ImageFile , new { htmlAttributes = new { @class = "form-control",@type = "file"} })*@
            <input type="file" name="ImageFile" class="form-control"/>
        </div>
        <br />
        <div style="text-align:right">
            <input class="btn btn-primary" value="Guardar" type="submit" />
        </div> 
    </div>
}